name: Build Release Artifacts

on:
  release:
    types:
      - published

jobs:
  build:
    timeout-minutes: 15 # Windows is such a special snowflake 🙂
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
      - name: 'Build'
        env:
          DESKTOP_PACKAGE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          ./gradlew packageDistributionForCurrentOS
      - name: 'Upload assets'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **/build/compose/binaries/main/dmg/*
            **/build/compose/binaries/main/deb/*
            **/build/compose/binaries/main/msi/*